/**
 * loader.js — module shell. DO NOT EDIT.
 *
 * Reads the manifest (modules/index.js), renders a tab bar,
 * and lazy-activates each feature module when its tab is clicked.
 *
 * Team members DO NOT edit this file.
 * They only touch modules/index.js and their own module file.
 */

import modules from "./modules/index.js";

(function boot() {
  const tabBar    = document.getElementById("tab-bar");
  const tabPanels = document.getElementById("tab-panels");
  const rendered  = new Set();

  modules.forEach((mod, i) => {
    // ── Tab button ──────────────────────────────────────────────────────────
    const btn = document.createElement("button");
    btn.className = "tab-btn" + (i === 0 ? " active" : "");
    btn.textContent = `${mod.icon ?? ""} ${mod.label}`;
    btn.dataset.id = mod.id;
    tabBar.appendChild(btn);

    // ── Panel ───────────────────────────────────────────────────────────────
    const panel = document.createElement("div");
    panel.className = "tab-panel" + (i === 0 ? " active" : "");
    panel.dataset.id = mod.id;
    tabPanels.appendChild(panel);

    // ── Tab click ───────────────────────────────────────────────────────────
    btn.addEventListener("click", () => {
      document.querySelectorAll(".tab-btn").forEach(b => b.classList.remove("active"));
      document.querySelectorAll(".tab-panel").forEach(p => p.classList.remove("active"));
      btn.classList.add("active");
      panel.classList.add("active");

      if (!rendered.has(mod.id)) {
        mod.render(panel);
        rendered.add(mod.id);
      }
    });

    // Auto-render first tab
    if (i === 0) {
      mod.render(panel);
      rendered.add(mod.id);
    }
  });
})();
