/**
 * data-ingest.js — Shared Data Management tab.
 *
 * Allows:
 *   1. Upload .parquet files
 *   2. Ingest JSON records (paste or type)
 *   3. Browse datasets + preview rows
 *   4. View schema of each dataset
 *
 * Shared module — DO NOT add feature-specific logic here.
 * Team members use this tab only to inspect/load data — do not edit this file.
 */

const API = "/api/data";

export default {
  id: "data",
  label: "Data",
  icon: "🗄️",

  render(container) {
    container.innerHTML = `
      <h2>🗄️ Data Management</h2>

      <!-- ── Upload parquet ─────────────────────────────────── -->
      <section>
        <h3>Upload Parquet File</h3>
        <input type="file" id="d-file" accept=".parquet" />
        <input type="text" id="d-dataset-name" placeholder="Dataset name (optional, defaults to filename)" style="margin-top:6px" />
        <br/>
        <button class="primary" id="d-upload">Upload</button>
        <div id="d-upload-status" class="status"></div>
      </section>

      <!-- ── Ingest JSON ────────────────────────────────────── -->
      <section>
        <h3>Ingest JSON Records</h3>
        <label>Dataset name (e.g. <code>feature_a/results</code>)</label>
        <input type="text" id="d-ingest-name" placeholder="feature_a/results" />
        <label style="margin-top:8px">Records (JSON array)</label>
        <textarea id="d-ingest-json" rows="6" placeholder='[{"col1": "val", "col2": 1.0}]'></textarea>
        <div style="display:flex;gap:8px;align-items:center;margin-top:4px">
          <label style="margin:0">Mode:</label>
          <select id="d-ingest-mode" style="padding:6px;border:1px solid #ccc;border-radius:4px;font-size:14px">
            <option value="append">append</option>
            <option value="overwrite">overwrite</option>
          </select>
          <button class="primary" id="d-ingest">Ingest</button>
        </div>
        <div id="d-ingest-status" class="status"></div>
      </section>

      <!-- ── Dataset browser ───────────────────────────────── -->
      <section>
        <h3>Datasets <button id="d-refresh" style="margin-left:8px;font-size:12px;padding:4px 10px">↻ Refresh</button></h3>
        <div id="d-datasets">Loading…</div>
      </section>

      <!-- ── Preview ───────────────────────────────────────── -->
      <section id="d-preview-section" style="display:none">
        <h3>Preview: <span id="d-preview-name"></span></h3>
        <div id="d-preview-schema" style="margin-bottom:8px;font-size:12px;color:#555"></div>
        <div style="overflow-x:auto">
          <table class="data-table" id="d-preview-table">
            <thead></thead><tbody></tbody>
          </table>
        </div>
      </section>
    `;

    this._bind(container);
    this._loadDatasets(container);
  },

  _bind(container) {
    container.querySelector("#d-upload").onclick  = () => this._upload(container);
    container.querySelector("#d-ingest").onclick  = () => this._ingest(container);
    container.querySelector("#d-refresh").onclick = () => this._loadDatasets(container);
  },

  // ── Upload ──────────────────────────────────────────────────────────────────
  async _upload(container) {
    const fileInput = container.querySelector("#d-file");
    const nameInput = container.querySelector("#d-dataset-name");
    const status    = container.querySelector("#d-upload-status");

    if (!fileInput.files.length) { status.textContent = "Select a file first."; return; }

    status.textContent = "Uploading…";
    status.className = "status";

    const fd = new FormData();
    fd.append("file", fileInput.files[0]);
    if (nameInput.value.trim()) fd.append("dataset", nameInput.value.trim());

    try {
      const resp = await fetch(`${API}/upload`, { method: "POST", body: fd });
      const data = await resp.json();
      if (resp.ok) {
        status.textContent = `✓ Uploaded "${data.dataset}" — ${data.rows} rows, ${data.columns} cols`;
        status.className = "status ok";
        this._loadDatasets(container);
      } else {
        status.textContent = `✗ ${data.detail}`;
        status.className = "status error";
      }
    } catch (err) {
      status.textContent = `✗ Network error: ${err.message}`;
      status.className = "status error";
    }
  },

  // ── Ingest JSON ─────────────────────────────────────────────────────────────
  async _ingest(container) {
    const name   = container.querySelector("#d-ingest-name").value.trim();
    const raw    = container.querySelector("#d-ingest-json").value.trim();
    const mode   = container.querySelector("#d-ingest-mode").value;
    const status = container.querySelector("#d-ingest-status");

    if (!name) { status.textContent = "Enter a dataset name."; return; }

    let records;
    try { records = JSON.parse(raw); }
    catch { status.textContent = "Invalid JSON."; status.className = "status error"; return; }

    if (!Array.isArray(records)) {
      status.textContent = "JSON must be an array of objects."; status.className = "status error"; return;
    }

    status.textContent = "Ingesting…"; status.className = "status";

    try {
      const resp = await fetch(`${API}/ingest`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dataset: name, records, mode }),
      });
      const data = await resp.json();
      if (resp.ok) {
        status.textContent = `✓ ${mode === "overwrite" ? "Wrote" : "Appended"} ${data.added} records → ${data.dataset}`;
        status.className = "status ok";
        this._loadDatasets(container);
      } else {
        status.textContent = `✗ ${data.detail}`; status.className = "status error";
      }
    } catch (err) {
      status.textContent = `✗ Network error: ${err.message}`; status.className = "status error";
    }
  },

  // ── Dataset list ────────────────────────────────────────────────────────────
  async _loadDatasets(container) {
    const el = container.querySelector("#d-datasets");
    el.textContent = "Loading…";

    let datasets;
    try {
      const resp = await fetch(`${API}/datasets`);
      if (!resp.ok) {
        const err = await resp.json().catch(() => ({}));
        el.innerHTML = `<p style="color:red">✗ Server error: ${err.detail ?? resp.statusText}</p>`;
        return;
      }
      datasets = await resp.json();
    } catch (err) {
      el.innerHTML = `<p style="color:red">✗ Network error: ${err.message}</p>`;
      return;
    }

    if (!datasets.length) {
      el.innerHTML = '<p style="color:#888;font-size:13px">No datasets yet. Upload a .parquet file or ingest JSON above.</p>';
      return;
    }

    el.innerHTML = `
      <table class="data-table">
        <thead><tr><th>Dataset</th><th>Rows</th><th>Size</th><th>Columns</th><th></th></tr></thead>
        <tbody>
          ${datasets.map(d => `
            <tr>
              <td><code>${d.name}</code></td>
              <td>${d.row_count}</td>
              <td>${_fmtBytes(d.size_bytes)}</td>
              <td>${Object.keys(d.columns || {}).join(", ")}</td>
              <td><button class="preview-btn" data-name="${d.name}" style="margin:0;padding:3px 10px;font-size:12px">Preview</button></td>
            </tr>
          `).join("")}
        </tbody>
      </table>
    `;

    el.querySelectorAll(".preview-btn").forEach(btn => {
      btn.onclick = () => this._preview(container, btn.dataset.name);
    });
  },

  // ── Preview ─────────────────────────────────────────────────────────────────
  async _preview(container, name) {
    const previewSection = container.querySelector("#d-preview-section");
    const schemaEl = container.querySelector("#d-preview-schema");

    try {
      const [previewResp, schemaResp] = await Promise.all([
        fetch(`${API}/preview?dataset=${encodeURIComponent(name)}&limit=50`),
        fetch(`${API}/schema?dataset=${encodeURIComponent(name)}`),
      ]);

      if (!previewResp.ok || !schemaResp.ok) {
        schemaEl.textContent = "Failed to load dataset.";
        previewSection.style.display = "";
        return;
      }

      const data       = await previewResp.json();
      const schemaData = await schemaResp.json();

      previewSection.style.display = "";
      container.querySelector("#d-preview-name").textContent = name;
      schemaEl.textContent = `Schema: ${Object.entries(schemaData.schema).map(([k,v]) => `${k} (${v})`).join(" · ")}`;

      const rows = data.rows;
      if (!rows.length) {
        container.querySelector("#d-preview-table").innerHTML = "<tbody><tr><td>Empty dataset</td></tr></tbody>";
        return;
      }

      const cols = Object.keys(rows[0]);
      const thead = container.querySelector("#d-preview-table thead");
      const tbody = container.querySelector("#d-preview-table tbody");

      thead.innerHTML = `<tr>${cols.map(c => `<th>${c}</th>`).join("")}</tr>`;
      tbody.innerHTML = rows.map(r =>
        `<tr>${cols.map(c => `<td>${r[c] ?? ""}</td>`).join("")}</tr>`
      ).join("");

      previewSection.scrollIntoView({ behavior: "smooth" });
    } catch (err) {
      schemaEl.textContent = `✗ Network error: ${err.message}`;
      previewSection.style.display = "";
    }
  },
};

function _fmtBytes(b) {
  if (b < 1024) return `${b} B`;
  if (b < 1024 ** 2) return `${(b / 1024).toFixed(1)} KB`;
  return `${(b / 1024 ** 2).toFixed(1)} MB`;
}
