"""
FastAPI app — auto-mounts all feature routers from agent/modules/.

Team members DO NOT edit this file.
They only add a router in agent/modules/__init__.py.
"""
import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from agent.modules import get_all_routers


def create_app(output_dir: str = "output") -> FastAPI:
    os.makedirs(output_dir, exist_ok=True)

    app = FastAPI(title="CP Agent", docs_url="/docs")
    # CORS: read allowed origins from env (comma-separated), default to localhost only.
    # Do NOT use allow_origins=["*"] with allow_credentials=True — browsers reject it
    # and it opens credentialed cross-site requests to any origin.
    _raw_origins = os.environ.get("ALLOWED_ORIGINS", "http://localhost:8080")
    _allowed_origins = [o.strip() for o in _raw_origins.split(",") if o.strip()]
    app.add_middleware(
        CORSMiddleware,
        allow_origins=_allowed_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ── Auto-register all feature routers ─────────────────────────────────────
    for router in get_all_routers():
        app.include_router(router)

    # ── Health check ──────────────────────────────────────────────────────────
    @app.get("/health")
    async def health():
        return {"status": "ok"}

    # ── Static frontend ───────────────────────────────────────────────────────
    frontend_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "frontend")
    if os.path.isdir(frontend_dir):
        app.mount("/", StaticFiles(directory=frontend_dir, html=True), name="frontend")

    return app
